[package]
name = "rparse"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3" # https://docs.rs/byteorder

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] } ## https://docs.rs/winapi
